version: "3.8"

services:
  web:
    container_name: fib_sequence_service
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 5000:5000
      - 8000:8000
    depends_on:
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  redis:
    image: redis:6-alpine
    container_name: api_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api

networks:
  web_api:
    driver: bridge