servergrpc:
  Port: :5000
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5
  Time: 120

serverhttp:
  Port: :8000
  ReadTimeout: 10
  WriteTimeout: 10

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0