// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/restlesswhy/grpc/grpc-rest-fibonacci-sequence/internal/fib/models"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetSeq mocks base method.
func (m *MockUseCase) GetSeq(ctx context.Context, from, to int32) (models.FibSeq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeq", ctx, from, to)
	ret0, _ := ret[0].(models.FibSeq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeq indicates an expected call of GetSeq.
func (mr *MockUseCaseMockRecorder) GetSeq(ctx, from, to interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeq", reflect.TypeOf((*MockUseCase)(nil).GetSeq), ctx, from, to)
}
