// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: internal/fib/proto/fib.proto

package fiboService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FiboRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From int32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To   int32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *FiboRequest) Reset() {
	*x = FiboRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fib_proto_fib_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiboRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiboRequest) ProtoMessage() {}

func (x *FiboRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fib_proto_fib_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiboRequest.ProtoReflect.Descriptor instead.
func (*FiboRequest) Descriptor() ([]byte, []int) {
	return file_internal_fib_proto_fib_proto_rawDescGZIP(), []int{0}
}

func (x *FiboRequest) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *FiboRequest) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

type FiboResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result map[int32]int64 `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *FiboResponse) Reset() {
	*x = FiboResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_fib_proto_fib_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiboResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiboResponse) ProtoMessage() {}

func (x *FiboResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_fib_proto_fib_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiboResponse.ProtoReflect.Descriptor instead.
func (*FiboResponse) Descriptor() ([]byte, []int) {
	return file_internal_fib_proto_fib_proto_rawDescGZIP(), []int{1}
}

func (x *FiboResponse) GetResult() map[int32]int64 {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_internal_fib_proto_fib_proto protoreflect.FileDescriptor

var file_internal_fib_proto_fib_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x66, 0x69, 0x62, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x66, 0x69, 0x62, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x46,
	0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x88,
	0x01, 0x0a, 0x0c, 0x46, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69,
	0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x39,
	0x0a, 0x0b, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x51, 0x0a, 0x13, 0x46, 0x69, 0x62,
	0x6f, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x18, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x66, 0x69, 0x62, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x46, 0x69, 0x62, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f, 0x5a, 0x0d,
	0x2e, 0x3b, 0x66, 0x69, 0x62, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_fib_proto_fib_proto_rawDescOnce sync.Once
	file_internal_fib_proto_fib_proto_rawDescData = file_internal_fib_proto_fib_proto_rawDesc
)

func file_internal_fib_proto_fib_proto_rawDescGZIP() []byte {
	file_internal_fib_proto_fib_proto_rawDescOnce.Do(func() {
		file_internal_fib_proto_fib_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_fib_proto_fib_proto_rawDescData)
	})
	return file_internal_fib_proto_fib_proto_rawDescData
}

var file_internal_fib_proto_fib_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_fib_proto_fib_proto_goTypes = []interface{}{
	(*FiboRequest)(nil),  // 0: fiboService.FiboRequest
	(*FiboResponse)(nil), // 1: fiboService.FiboResponse
	nil,                  // 2: fiboService.FiboResponse.ResultEntry
}
var file_internal_fib_proto_fib_proto_depIdxs = []int32{
	2, // 0: fiboService.FiboResponse.result:type_name -> fiboService.FiboResponse.ResultEntry
	0, // 1: fiboService.FiboSequenceService.Get:input_type -> fiboService.FiboRequest
	1, // 2: fiboService.FiboSequenceService.Get:output_type -> fiboService.FiboResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_fib_proto_fib_proto_init() }
func file_internal_fib_proto_fib_proto_init() {
	if File_internal_fib_proto_fib_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_fib_proto_fib_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiboRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_fib_proto_fib_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiboResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_fib_proto_fib_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_fib_proto_fib_proto_goTypes,
		DependencyIndexes: file_internal_fib_proto_fib_proto_depIdxs,
		MessageInfos:      file_internal_fib_proto_fib_proto_msgTypes,
	}.Build()
	File_internal_fib_proto_fib_proto = out.File
	file_internal_fib_proto_fib_proto_rawDesc = nil
	file_internal_fib_proto_fib_proto_goTypes = nil
	file_internal_fib_proto_fib_proto_depIdxs = nil
}
